// Test stubs — living spec (Decision #10)

// describe("BotConfig", () => {
//   test.todo("decode valid JSON returns Ok(botConfig)")
//   test.todo("decode missing tradingMode returns ConfigError MissingField")
//   test.todo("decode invalid tradingMode returns ConfigError InvalidValue")
//   test.todo("decode missing exchange object returns ConfigError MissingField")
//   test.todo("decode invalid exchangeId returns ConfigError InvalidValue")
//   test.todo("decode missing symbols returns ConfigError MissingField")
//   test.todo("decode non-string symbols returns ConfigError InvalidValue")
//   test.todo("decode missing riskLimits returns ConfigError MissingField")
//   test.todo("decode missing riskLimits.maxPositionSize returns ConfigError MissingField")
//   test.todo("decode missing riskLimits.maxOpenPositions returns ConfigError MissingField")
//   test.todo("decode missing riskLimits.maxDailyLoss returns ConfigError MissingField")
//   test.todo("decode non-object JSON returns ConfigError ParseFailed")
//   test.todo("loadFromFile with nonexistent path returns ConfigError FileNotFound")
//   test.todo("round-trip: valid config encodes and decodes to same value")
// })
